application: ist-nova
version: 1
runtime: python27
api_version: 1
threadsafe: true
skip_files: |
 ^(.*/)?(
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 )$

handlers:
- url: /.*
  script: main.app
  
libraries:
- name: jinja2
  version: latest  