application: ist-nova
version: 1
runtime: python27
api_version: 1
threadsafe: false
skip_files: |
 ^(.*/)?(
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 )$


  
libraries:
- name: jinja2
  version: latest  
  



handlers:

- url: /static
  static_dir: static
  
  
- url: /.*
  script: main.app


- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: optional



  

